### ISSUE TITLE
Providing PDF buffer rather than file name

### ISSUE THREAD

**Issue by ercint** [artiebits/pdf-to-printer#247]
First of all thanks for pdf-to-printer.

We would like to provide pdf buffer to your print constructor. Now it is not available, are you planning to implement this feature?

Regards

**Comment by artiebits** [comment]
hi @ercint, i didn't plan to implement it but you are more than welcome to contribute to this project. I would appreciate it!

**Comment by m4heshd** [comment]
This is a vital feature that would make this module unavoidable since more than 80% of the time, developers are dealing with in-memory data rather than files. People hardly like to incorporate filesystem transactions unless there's a critical requirement. I wish I had the time right now to integrate this feature.

**Comment by ferretwithaberet** [comment]
Even if the package will provide this, under the hood it will still create a temporary file. Also, I am not sure if we can implement this yet because there is no way to know when the printing job finished and I do not think we can remove that temporary file before the printing job ends.
