### ISSUE TITLE
Ability to get event when printing is done

### ISSUE THREAD

**Issue by gallyamow** [artiebits/pdf-to-printer#251]
Hi.

I need to know is my print job finished or not.
My solution is using `lpstat`  for monitoring the printing queue and emit an event when the job disappeared or failed
Is it implemented yet?
Thank you

**Comment by ferretwithaberet** [comment]
> Hi.
> 
> I need to know is my print job finished or not.
> My solution is using `lpstat` for monitoring the printing queue and emit an event when the job disappeared or failed
> Is it implemented yet?
> Thank you

I thought about this too, it is not that easy because using `lpstat` to monitor the printing queue would mean to execute it every `x` time to check if something about the job changed which in my opinion is not a great implementation. I am looking for a way to wait for the printing job to finish but I did not find one yet.

**Comment by gallyamow** [comment]
Thank you for your response.

**Comment by gallyamow** [comment]
ok
