### ISSUE TITLE
Http pdfs

### ISSUE THREAD

**Issue by darinw** [artiebits/pdf-to-printer#257]
This package is everything i have been looking for! The only problem is i am trying to print a PDF that i download from our server. The exact URL i am running attempting is https://tournamentdepot.com/servlet/PdfServlet?id=Tournament0000000266&multiGames=Bracket0000002223-Game0000035352

I am not very familiar with electron so my first thoughts are that i would need download my pdf and store it in a temp directory then reference that with printer.print('temp/generatedPdf.pdf')

It seems like a common thing to want to download a pdf from http? Do you have any thoughts on if it would be a good addition to pdf-to-printer?

**Comment by artiebits** [comment]
Hi @darinw, thanks for your sharing your idea with me. 

I would like to keep pdf-to-printer as small as possible and stick to it's main purpose - printing PDF files from Node application, because maintaining this package and giving support to developers/companies that use it already takes some of my free time.
Functionality to download and remove files can be easily implemented by yourself. You can take a look at this example  https://github.com/artiebits/pdf-to-printer/blob/master/examples/express-server/src/print.js#L28.

Thanks again for sharing your idea with me, and sorry that I don't want to implement it!

**Comment by darinw** [comment]
Awesome thank you for the example! Again, love the project, keep it up!
