### ISSUE TITLE
Support paperSize A7

### ISSUE THREAD

**Issue by sassouiabd** [artiebits/pdf-to-printer#406]
I would like to print documents on 7.2cm width, the nearest paperSize is the A7 format
Is it possible to support this size or is there a workaround ?

**Comment by artiebits** [comment]
Hi @sassouiabd, sorry for the delay in response. 

There was a PR to remove paperSize validation because you can pass any size but that PR was not finished so I closed it https://github.com/artiebits/pdf-to-printer/pull/370. Let me know if you would like to finish it, otherwise I will do it this weekend

**Comment by artiebits** [comment]
hi @sassouiabd, I have published a beta version `pdf-to-printer-5.4.1-beta.0`. could you please try it and let me know if it work for you?
